ARG FEDORA_VERSION=44

FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN dnf upgrade -y 'kernel*' --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y \
https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
sh -c 'echo "%_without_kmod_nvidia_detect 1" > /etc/rpm/macros.nvidia-kmod' && \
dnf install -y akmod-nvidia-580xx && \
akmods --kernels "$KERNEL_VERSION" --force

FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION} AS final
# Adiciona labels do ostree
LABEL ostree.bootable="true"
LABEL containers.bootc="1"
# Muda diretório de trabalho
WORKDIR /tmp/build-context
# Copia lista de pacotes
COPY packages/dnf* ./
# Pacotes extras
RUN dnf install -y \
https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo && \
dnf upgrade -y --refresh && \
tr '\n' ' ' < dnf-install-packages-with-nvidia | xargs dnf install -y
# Módulos
COPY --from=builder /var/cache/akmods/nvidia-580xx/kmod-nvidia*.rpm ./
COPY builds/nvidia-legacy-580xx/1-nvidia-args.toml ./
RUN dnf -y install ./kmod-nvidia*.rpm xorg-x11-drv-nvidia-580xx-cuda --setopt=install_weak_deps=False && \
mv -v 1-nvidia-args.toml /usr/lib/bootc/kargs.d/1-nvidia-args.toml
# Secure Boot
ARG SECUREBOOT=true
COPY scripts/secureboot/ ./secureboot/
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT_IGNORE" = true ]; then \
        mkdir -p ./.actions; \
        cp -r /context/.actions/* ./secureboot/; \
        bash ./secureboot/sign-modules.sh; \
fi'
# Fase de limpeza
RUN rm -rvf /tmp/build-context && \
dnf clean all && \
rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/* 
# Volta pra raiz
WORKDIR /

RUN bootc container lint