ARG FEDORA_VERSION=44

FROM quay.io/fedora/fedora-bootc:${FEDORA_VERSION} AS builder
RUN dnf upgrade -y 'kernel*' --refresh && \
KERNEL_VERSION="$(rpm -q kernel-core --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}')" && \
dnf install -y 'dnf5-command(config-manager)' && \
dnf install -y fedora-workstation-repositories && \
dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf install -y akmod-nvidia && \
akmods --kernels "$KERNEL_VERSION" --force

FROM quay.io/fedora/fedora-silverblue:${FEDORA_VERSION} AS final
# Adiciona labels do ostree
LABEL ostree.bootable="true"
LABEL containers.bootc="1"
WORKDIR /tmp/build-context

# Copia lista de pacotes e módulos compilados
COPY packages/dnf* ./
# Pacotes
RUN dnf config-manager setopt rpmfusion-nonfree-nvidia-driver.enabled=1 && \
dnf config-manager addrepo -y --from-repofile=https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo && \
tr '\n' ' ' < dnf-install-packages-with-nvidia | xargs dnf install -y --nogpgcheck
# Módulos
COPY --from=builder /var/cache/akmods/nvidia/kmod-nvidia*.rpm ./
COPY builds/nvidia-open/1-nvidia-args.toml ./
RUN dnf -y install ./kmod-nvidia*.rpm xorg-x11-drv-nvidia-cuda --setopt=install_weak_deps=False && \
mv -v 1-nvidia-args.toml /usr/lib/bootc/kargs.d/1-nvidia-args.toml
# Assinatura Secure Boot
ARG SECUREBOOT=true
COPY scripts/secureboot/ ./secureboot/
RUN --mount=type=bind,source=.,target=/context \
/bin/bash -c 'if [ "$SECUREBOOT" = true ]; then \
        mkdir -p ./.actions; \
        cp -r /context/.actions/* ./secureboot/; \
        bash ./secureboot/sign-modules.sh; \
fi'
# Fase de limpeza
RUN rm -rvf /tmp/build-context && \
dnf clean all && \
rm -rfv /var/cache/* \
        /var/lib/* \
        /var/log/* \
        /var/tmp/* 
# Volta pra raiz
WORKDIR /

RUN bootc container lint