name: nvidia-legacy-580xx build

on:
  schedule:
    - cron: '15 0 * * 1'
      timezone: 'America/Sao_Paulo' 
  workflow_dispatch:
    inputs:
      fedora_version:
        description: 'Versão do Fedora Silverblue'
        default: '44'
        required: false

env:
  IMAGE_NAME: fedora-silverblue-nvidia-legacy-580xx
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-push:
    runs-on: ubuntu-26.04
    env:
      SELECTED_VERSION: ${{ github.event.inputs.fedora_version || '44' }}
      DEFAULT_VERSION: '44'
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Gerar metadados do build
        id: meta
        run: |
          VERSION=${{ env.SELECTED_VERSION }}
          DATE=$(TZ='America/Sao_Paulo' date +'%Y%m%d.%H%M')
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          KERNEL_VERSION=$(sudo podman run quay.io/fedora/fedora-bootc:${VERSION} bash -c 'dnf upgrade -y "kernel*" >/dev/null && \
            rpm -q kernel-core --queryformat "%{VERSION}-%{RELEASE}.%{ARCH}"')
          if [ "${{ env.SELECTED_VERSION }}" -gt "${{ env.DEFAULT_VERSION }}" ]; then
            echo "channel=beta" >> $GITHUB_OUTPUT
          elif [ "${{ env.SELECTED_VERSION }}" -eq "${{ env.DEFAULT_VERSION }}" ]; then
            echo "channel=latest" >> $GITHUB_OUTPUT
          else
            echo "channel=old" >> $GITHUB_OUTPUT
          fi
          echo "version=${VERSION}"     >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "date=${DATE}"     >> $GITHUB_OUTPUT
          echo "kernel_version=$KERNEL_VERSION" >> $GITHUB_OUTPUT
      
      - name: Login no GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | sudo podman login \
            -u "${{ github.actor }}" --password-stdin "${{ env.REGISTRY }}"

      - name: Pega Key do Repo
        env:
          PRIVATEKEY_BASE64: ${{ secrets.SECURE_BOOT_KEY }}
        run: |
            mkdir -p .actions
            echo -n "$PRIVATEKEY_BASE64" | base64 --decode > .actions/MOK.priv
            
      - name: Build da imagem inicial (como root)
        run: |
          sudo podman build \
            --skip-unused-stages=false \
            --security-opt label=disable \
            -t "localhost/bootc-raw:latest" \
            -f ./builds/nvidia-legacy-580xx/Containerfile \
            -v "$(pwd):/run/src" \
            --build-arg FEDORA_VERSION=${{ env.SELECTED_VERSION }} \
            .

      - name: Rechunk via bootc-base-imagectl e remoção
        run: |
          sudo podman run --rm --privileged \
            -v /var/lib/containers:/var/lib/containers \
            quay.io/fedora/fedora-bootc:44 \
            /usr/libexec/bootc-base-imagectl rechunk \
            localhost/bootc-raw:latest \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SELECTED_VERSION }}
          sudo podman rmi localhost/bootc-raw:latest

      - name: Tags e Push da imagem
        run: |
          REGISTRY_IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
          PRIMARY_TAG="${{ env.SELECTED_VERSION }}"
          PRIMARY_IMAGE="${REGISTRY_IMAGE}:${PRIMARY_TAG}"

          sudo skopeo copy \
            containers-storage:${PRIMARY_IMAGE} \
            docker://${PRIMARY_IMAGE}

          for TAG in "${{ steps.meta.outputs.version }}.${{ steps.meta.outputs.date }}" \
                     "${{ steps.meta.outputs.short_sha }}" \
                     "${{ steps.meta.outputs.channel }}" \
                     "${{ github.sha }}" \
                     "${{ steps.meta.outputs.kernel_version }}"; do
            
            [ -z "$TAG" ] || [ "$TAG" = "$PRIMARY_TAG" ] && continue
            
            sudo skopeo copy \
              docker://${PRIMARY_IMAGE} \
              docker://${REGISTRY_IMAGE}:${TAG}
          done
